#!/bin/bash
NA_MAIN_GROUP="www-data"
NA_MAIN_USER="rene"
NA_MAIN_PERMISSIONS=750
NA_USERDATA_PERMISSIONS=770
NA_MAIN_HTDOCS_RELATIVE_PATH="data1/htdocs"
NA_MAIN_SITE_FOLDER="localhost_v2"
NA_SITE_APPS=( restart_newsApp.sh )
